---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-api-aws
  name: cluster-api-aws
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://openinfradev.github.io/helm-repo
    name: cluster-api-aws
    version: 0.4.0
  releaseName: cluster-api-aws
  targetNamespace: argo
  values:
    sshKeyName: TO_BE_FIXED
    cluster:
      name: TO_BE_FIXED
      region: TO_BE_FIXED
      kubernetesVersion: v1.22.5
      podCidrBlocks:
      - 10.10.0.0/16
      bastion:
        enabled: true
        instanceType: t3.micro
        allowedCIDRBlocks:
        - 127.0.0.1/32
        useSpotInstance:
          enabled: true
    kubeadmControlPlane:
      replicas: 3
      controlPlaneMachineType: TO_BE_FIXED
      rootVolume:
        size: 20 # GB
        type: gp2
    machinePool: []
    machineDeployment: []
    job:
      taconode:
        enabled: true
        labels:
        - taco-lma
        - taco-ingress-gateway
        - taco-egress-gateway
        - servicemesh
      argo:
        enabled: true
        url: TO_BE_FIXED  # argocd url like argocd-v2.taco-cat.xyz
        user: admin
        password: TO_BE_FIXED  
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubernetes-addons
  name: kubernetes-addons
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://openinfradev.github.io/helm-repo
    name: kubernetes-addons
    version: 0.1.0
  releaseName: kubernetes-addons
  targetNamespace: taco-system
  values:
    cni:
      calico:
        enabled: true
    csi:
      aws-ebs:
        enabled: false
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: aws-ebs-csi-driver
  name: aws-ebs-csi-driver
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    name: aws-ebs-csi-driver
    version: 2.6.3
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
  values:
    storageClasses:
    - name: taco-storage
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      volumeBindingMode: WaitForFirstConsumer
      parameters:
        encrypted: "true"
        type: gp3
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: ingress-nginx
  name: ingress-nginx
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.0.17
  releaseName: ingress-nginx
  targetNamespace: taco-system
  values:
    controller:
      hostPort:
        enabled: true
      service:
        externalTrafficPolicy: Local
        nodePorts:
          http: 32080
          https: 32443
          tcp:
            "10254": 32081
        type: NodePort
    tcp:
      "10254": 10254:healthz
  wait: true
# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   labels:
#     name: kubeseal
#   name: kubeseal
# spec:
#   helmVersion: v3
#   chart:
#     type: helmrepo
#     repository: 
#     name: kubeseal
#     version: 0.1.0
#   releaseName: kubeseal
#   targetNamespace: taco-system
#   values:

#   wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubed 
  name: kubed
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://charts.appscode.com/stable
    name: kubed
    version: v0.12.0
  releaseName: kubed
  targetNamespace: taco-system
  values:

  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-autoscaler
  name: cluster-autoscaler
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://openinfradev.github.io/helm-repo
    name: cluster-autoscaler
    version: 0.1.0
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  values:
    separateMgmtClusterEnabled: true
    discoveryNamespace: TO_BE_FIXED
    discoveryClusterName: TO_BE_FIXED
    mgmtKubeconfigSecretName: mgmt-kubeconfig
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: metrics-server
  name: metrics-server
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://kubernetes-sigs.github.io/metrics-server/
    name: metrics-server
    version: 3.8.2
  releaseName: metrics-server
  targetNamespace: lma
  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      # a value 'tag' is guided in https://artifacthub.io/packages/helm/metrics-server/metrics-server but not applied on any template
      # tag: ""
      pullPolicy: IfNotPresent
    args:
      - --kubelet-insecure-tls